<?php
use Drupal\custom\Plugin\Block\AWBlock;

/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

function bstrap_child_preprocess_html(&$toVariables)
{
  $loNode = \Drupal::request()->attributes->get('node');
  if ($loNode == null)
  {
    return;
  }

  $lnID = $loNode->id();
  $lcType = $loNode->getType();

  $lcTitle = $loNode->getTitle() . ' | ' . \Drupal::config('system.site')->get('name');
  $lcHost = \Drupal::request()->getSchemeAndHttpHost();
  $lcURL = $lcHost . \Drupal::service('path.alias_manager')->getAliasByPath('/node/' . $lnID);


  $loTitleTag = [
      '#tag' => 'meta',
      '#attributes' => [
          'property' => 'og:title',
          'content' => $lcTitle,
      ],
  ];

  $loTypeTag = [
      '#tag' => 'meta',
      '#attributes' => [
          'property' => 'og:type',
          'content' => 'website',
      ],
  ];

  $loURLTag = [
      '#tag' => 'meta',
      '#attributes' => [
          'property' => 'og:url',
          'content' => $lcURL,
      ],
  ];

  $toVariables['page']['#attached']['html_head'][] = [$loTitleTag, 'facebook1'];
  $toVariables['page']['#attached']['html_head'][] = [$loTypeTag, 'facebook2'];
  $toVariables['page']['#attached']['html_head'][] = [$loURLTag, 'facebook3'];

  if (strcasecmp($lcType, 'blog') == 0)
  {
    $loReferencedParagraph = AWBlock::getReferencedEntity($loNode, 'field_row_of_image_text');
    $loReferencedImage = AWBlock::getReferencedEntity($loReferencedParagraph, 'field_image_content_id');
    $lcImage = $lcHost . AWBlock::getNodeField($loReferencedImage, 'field_image');

    $loImgTag = [
        '#tag' => 'meta',
        '#attributes' => [
            'property' => 'og:image',
            'content' => $lcImage,
        ],
    ];
    $toVariables['page']['#attached']['html_head'][] = [$loImgTag, 'facebook4'];
  }
}
